"""Anonymized telemetry store — Supabase (PostgREST) via httpx.

This module implements two operations against a single `signals` table:
  - `log_signal(record)` — best-effort insert. Fires in a background thread so
    the request path is never blocked, and swallows every exception. If
    Supabase is misconfigured / down / slow, /analyze responses are UNAFFECTED.
  - `get_trends()` — aggregate read for the Trends dashboard. Falls back to a
    valid empty shape with status="unavailable" when the store isn't reachable.

Contract with the caller: `record` MUST already be the anonymized record from
`core.privacy.to_anonymized_record(...)`. This module does not sanitize input;
it trusts the whitelist upstream.

# ------------------------------------------------------------
# Supabase DDL — paste this into the Supabase SQL editor:
# ------------------------------------------------------------
# create table if not exists public.signals (
#     id           bigint generated by default as identity primary key,
#     created_at   timestamptz not null default now(),
#     scam_type    text        not null,
#     risk_bucket  text        not null check (risk_bucket in ('low','medium','high')),
#     detected_language text   not null,
#     decision_source   text   not null,
#     fallback_used     boolean not null default false
# );
# create index if not exists signals_created_at_idx on public.signals (created_at desc);
# -- Row-level security: enable and grant the service_role bypass. The
# -- SUPABASE_SERVICE_KEY used by this backend is the service_role key, which
# -- bypasses RLS. The anon key must NEVER be given to this backend.
# alter table public.signals enable row level security;
# ------------------------------------------------------------
#
# `audit_log` is a SEPARATE table with a DELIBERATELY WIDER field contract
# than `signals` above — it exists for legal admissibility (law enforcement
# / the user proving a specific message was analyzed), not anonymized
# telemetry, so it is keyed by case_id and carries a few more derived fields.
# It still never stores raw message text: `input_hash` is a one-way
# SHA-256 of the input, and `matched_pattern_ids` is a comma-separated list
# of KB entry IDs (e.g. "DA-01,DA-03"), not the matched text itself.
#
# ------------------------------------------------------------
# Supabase DDL — paste this into the Supabase SQL editor (also in
# deploy/supabase_audit.sql):
# ------------------------------------------------------------
# create table if not exists public.audit_log (
#     case_id             text primary key,
#     scam_type           text,
#     risk_bucket         text,
#     confidence_bucket   text,   -- 'high' (>0.8), 'medium' (0.5-0.8), 'low' (<0.5)
#     decision_source     text,
#     detected_language   text,
#     matched_pattern_ids text,   -- comma-separated KB entry IDs, e.g. "DA-01,DA-03"
#     fallback_used       boolean,
#     input_hash          text,   -- SHA-256 hex digest of the input text, NOT the text
#     created_at          timestamptz not null default now()
# );
# create index if not exists audit_log_created_at_idx on public.audit_log (created_at desc);
# alter table public.audit_log enable row level security;
# ------------------------------------------------------------
"""

from __future__ import annotations

import logging
import threading
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from typing import Any, Iterable

import httpx

from core.config import settings

log = logging.getLogger(__name__)

_TABLE = "signals"
_AUDIT_TABLE = "audit_log"
_INSERT_TIMEOUT_S = 4.0     # tight — telemetry is fire-and-forget
_READ_TIMEOUT_S = 8.0       # trends endpoint is user-visible; give it a bit more
_TRENDS_ROW_LIMIT = 10_000  # cap the trends read — we only need coarse counts
_CASE_LOOKUP_TIMEOUT_S = 8.0  # /case/{case_id} is user/law-enforcement-visible


# ---------------------------------------------------------------------------
# Availability check
# ---------------------------------------------------------------------------

def _is_configured() -> bool:
    return bool(settings.supabase_url and settings.supabase_service_key)


def _rest_url() -> str:
    base = settings.supabase_url.rstrip("/")
    return f"{base}/rest/v1/{_TABLE}"


def _audit_rest_url() -> str:
    base = settings.supabase_url.rstrip("/")
    return f"{base}/rest/v1/{_AUDIT_TABLE}"


def _headers(*, prefer_return_minimal: bool = True) -> dict:
    h = {
        "apikey": settings.supabase_service_key,
        "Authorization": f"Bearer {settings.supabase_service_key}",
        "Content-Type": "application/json",
    }
    if prefer_return_minimal:
        h["Prefer"] = "return=minimal"
    return h


# ---------------------------------------------------------------------------
# Insert — fire-and-forget
# ---------------------------------------------------------------------------

def _do_insert(record: dict) -> None:
    """Perform the actual HTTP POST. Runs in a worker thread."""
    try:
        with httpx.Client(timeout=_INSERT_TIMEOUT_S) as client:
            resp = client.post(_rest_url(), headers=_headers(), json=record)
            if resp.status_code >= 300:
                # Log a compact one-liner; do not include response body since
                # Supabase can echo the payload back on some errors and we
                # want zero leakage even into logs.
                log.warning(
                    "signals insert failed: HTTP %s (%s)",
                    resp.status_code,
                    resp.reason_phrase,
                )
    except Exception as e:
        # NEVER let telemetry escape into the request path.
        log.warning("signals insert error: %s", e)


def log_signal(record: dict) -> None:
    """Insert an anonymized `record` into the `signals` table.

    Non-blocking: dispatches the write to a background daemon thread so the
    /analyze response is not held up by Supabase latency. Every failure mode
    (unconfigured, DNS failure, 4xx/5xx, timeout) is swallowed and logged.

    Callers MUST pass an already-anonymized record from
    `core.privacy.to_anonymized_record(...)`.
    """
    if not _is_configured():
        return
    if not isinstance(record, dict) or not record:
        return
    try:
        t = threading.Thread(
            target=_do_insert,
            args=(record,),
            name="kavach-signals-write",
            daemon=True,
        )
        t.start()
    except Exception as e:
        log.warning("failed to dispatch signals insert: %s", e)


# ---------------------------------------------------------------------------
# Trends aggregation
# ---------------------------------------------------------------------------

def _empty_trends(status: str = "empty") -> dict:
    return {
        "status": status,             # "ok" | "empty" | "unavailable"
        "total_count": 0,
        "by_scam_type": {},
        "by_risk_bucket": {"low": 0, "medium": 0, "high": 0},
        "by_language": {},
        "by_decision_source": {},
        "fallback_used_count": 0,
        "last_7_days": [],            # list of {date: 'YYYY-MM-DD', count: N}
    }


def _fetch_rows() -> list[dict] | None:
    """Fetch recent rows from Supabase. Returns None on any failure."""
    if not _is_configured():
        return None
    since = (datetime.now(timezone.utc) - timedelta(days=30)).isoformat()
    url = _rest_url()
    params = {
        "select": "scam_type,risk_bucket,detected_language,decision_source,fallback_used,created_at",
        "created_at": f"gte.{since}",
        "order": "created_at.desc",
        "limit": str(_TRENDS_ROW_LIMIT),
    }
    try:
        with httpx.Client(timeout=_READ_TIMEOUT_S) as client:
            resp = client.get(url, headers=_headers(prefer_return_minimal=False), params=params)
            if resp.status_code >= 300:
                log.warning(
                    "signals read failed: HTTP %s (%s)",
                    resp.status_code,
                    resp.reason_phrase,
                )
                return None
            data = resp.json()
            if not isinstance(data, list):
                log.warning("signals read: unexpected response shape (not a list)")
                return None
            return data
    except Exception as e:
        log.warning("signals read error: %s", e)
        return None


def _last_7_days_series(rows: Iterable[dict]) -> list[dict]:
    """Return per-day counts for the last 7 days, oldest-first, filling zero days."""
    today = datetime.now(timezone.utc).date()
    buckets: dict = {(today - timedelta(days=i)): 0 for i in range(6, -1, -1)}
    for r in rows:
        ts = r.get("created_at")
        if not ts:
            continue
        try:
            # Postgres timestamptz -> parseable ISO string, with trailing +00
            day = datetime.fromisoformat(ts.replace("Z", "+00:00")).date()
        except Exception:
            continue
        if day in buckets:
            buckets[day] += 1
    return [{"date": d.isoformat(), "count": n} for d, n in buckets.items()]


def aggregate(rows: list[dict]) -> dict:
    """Aggregate a list of anonymized rows into the trends response shape.

    Kept as a top-level function so tests can exercise it without touching
    the network.
    """
    out = _empty_trends(status="empty")
    if not rows:
        return out

    scam_counter: Counter = Counter()
    risk_counter: Counter = Counter()
    lang_counter: Counter = Counter()
    decision_counter: Counter = Counter()
    fallback_true = 0

    for r in rows:
        scam_counter[r.get("scam_type") or "unknown"] += 1
        risk_counter[r.get("risk_bucket") or "low"] += 1
        lang_counter[r.get("detected_language") or "en"] += 1
        decision_counter[r.get("decision_source") or "unknown"] += 1
        if bool(r.get("fallback_used")):
            fallback_true += 1

    out["status"] = "ok"
    out["total_count"] = len(rows)
    out["by_scam_type"] = dict(sorted(scam_counter.items(), key=lambda x: -x[1]))
    # Ensure the three risk buckets always appear, even at zero.
    risk_defaults = {"low": 0, "medium": 0, "high": 0}
    risk_defaults.update({k: v for k, v in risk_counter.items() if k in risk_defaults})
    out["by_risk_bucket"] = risk_defaults
    out["by_language"] = dict(sorted(lang_counter.items(), key=lambda x: -x[1]))
    out["by_decision_source"] = dict(sorted(decision_counter.items(), key=lambda x: -x[1]))
    out["fallback_used_count"] = fallback_true
    out["last_7_days"] = _last_7_days_series(rows)
    return out


def get_trends() -> dict:
    """Aggregate view for /trends. Never raises; on failure returns an empty
    shape with status='unavailable'."""
    try:
        rows = _fetch_rows()
        if rows is None:
            out = _empty_trends(status="unavailable")
            return out
        return aggregate(rows)
    except Exception as e:  # defensive
        log.warning("get_trends unexpected failure: %s", e)
        return _empty_trends(status="unavailable")


# ---------------------------------------------------------------------------
# Audit log — legal-admissibility trail, separate table from `signals`
# ---------------------------------------------------------------------------

def _do_audit_insert(record: dict) -> None:
    """Perform the actual HTTP POST to audit_log. Runs in a worker thread."""
    try:
        with httpx.Client(timeout=_INSERT_TIMEOUT_S) as client:
            resp = client.post(_audit_rest_url(), headers=_headers(), json=record)
            if resp.status_code >= 300:
                log.warning(
                    "audit_log insert failed: HTTP %s (%s)",
                    resp.status_code,
                    resp.reason_phrase,
                )
    except Exception as e:
        # NEVER let the audit write escape into the request path.
        log.warning("audit_log insert error: %s", e)


def log_audit_record(record: dict) -> None:
    """Insert a case audit `record` into the `audit_log` table.

    Same fire-and-forget discipline as log_signal(): dispatched to a
    background daemon thread, every failure mode swallowed and logged. The
    caller's Verdict is unaffected whether or not this write succeeds.

    Callers pass the already-assembled audit dict (case_id, scam_type,
    risk_bucket, confidence_bucket, decision_source, detected_language,
    matched_pattern_ids, fallback_used, input_hash) — this module does not
    validate or reshape it beyond checking it's a non-empty dict.
    """
    if not _is_configured():
        return
    if not isinstance(record, dict) or not record:
        return
    try:
        t = threading.Thread(
            target=_do_audit_insert,
            args=(record,),
            name="kavach-audit-write",
            daemon=True,
        )
        t.start()
    except Exception as e:
        log.warning("failed to dispatch audit_log insert: %s", e)


class AuditStoreUnavailable(Exception):
    """Raised by get_audit_record() when Supabase is unconfigured, unreachable,
    or errors — distinct from a clean "0 rows" result, so routes/analyze.py
    can return 503 instead of misreporting a store outage as 404."""


def get_audit_record(case_id: str) -> dict | None:
    """Fetch the audit_log row for `case_id`. Synchronous — this backs the
    user/law-enforcement-facing GET /case/{case_id} endpoint, so unlike
    log_audit_record() it does need to report its outcome to the caller.

    Returns the row dict, or None if genuinely not found (0 rows).
    Raises AuditStoreUnavailable if Supabase is unconfigured/unreachable/
    erroring — callers should map that to 503, not 404.
    """
    if not _is_configured():
        raise AuditStoreUnavailable("Supabase is not configured")
    try:
        with httpx.Client(timeout=_CASE_LOOKUP_TIMEOUT_S) as client:
            resp = client.get(
                _audit_rest_url(),
                headers=_headers(prefer_return_minimal=False),
                params={"case_id": f"eq.{case_id}", "select": "*", "limit": "1"},
            )
            if resp.status_code >= 300:
                log.warning(
                    "audit_log read failed: HTTP %s (%s)",
                    resp.status_code,
                    resp.reason_phrase,
                )
                raise AuditStoreUnavailable(f"HTTP {resp.status_code}")
            data = resp.json()
            if not isinstance(data, list):
                log.warning("audit_log read: unexpected response shape (not a list)")
                raise AuditStoreUnavailable("unexpected response shape")
            if not data:
                return None
            return data[0]
    except AuditStoreUnavailable:
        raise
    except Exception as e:
        log.warning("audit_log read error: %s", e)
        raise AuditStoreUnavailable(str(e)) from e
