-- Kavach — anonymized telemetry table (Phase 3).
-- Paste this whole file into the Supabase SQL editor and run.
--
-- Privacy note: the schema itself enforces that no user message text can be
-- persisted. The five whitelisted columns below plus `created_at` are the
-- entire surface area. There is no free-form `payload` / `metadata` / `raw`
-- column.

create table if not exists public.signals (
    id                bigint generated by default as identity primary key,
    created_at        timestamptz not null default now(),
    scam_type         text        not null,
    risk_bucket       text        not null check (risk_bucket in ('low', 'medium', 'high')),
    detected_language text        not null,
    decision_source   text        not null,
    fallback_used     boolean     not null default false
);

-- Trends queries filter by `created_at`; this index makes the recent-window
-- read cheap.
create index if not exists signals_created_at_idx
    on public.signals (created_at desc);

-- Turn on Row-Level Security. The Kavach backend uses the `service_role` key
-- which bypasses RLS server-side; the anon key never sees this table.
alter table public.signals enable row level security;
